# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  movietheaterbackend:
    image: movietheaterbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5071:5071

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_Buckets: movies, posters
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: movie_db
    volumes:
      - pgdata:/var/lib/postgresql/data
